name: CD - Build and Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64, x86, ARM64]

    runs-on: windows-latest

    env:
      Project_Path: quickLink/quickLink.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application
    - name: Restore the application
      run: dotnet restore $env:Project_Path

    # Build the application
    - name: Build the application
      run: dotnet build $env:Project_Path -c $env:Configuration -p:Platform=$env:Platform
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}

    # Publish the application (creates MSIX package)
    - name: Publish the application
      run: dotnet publish $env:Project_Path -c $env:Configuration -p:Platform=$env:Platform
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}

    # Upload the build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quickLink-${{ matrix.platform }}-${{ matrix.configuration }}
        path: quickLink/bin/${{ matrix.configuration }}/
